# Generated by Django 3.1.1 on 2020-10-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
